### PR TITLE
Maybe add support for v2 scheduler

### PR DESCRIPTION
**Pull request by TooYoungTooSimp**
#52 
We can update anki-bundled to 2.1.16 without modify any other code.

### CODE REVIEW

**Comment by tsdko** [comment]
Is there any reason to upgrade other than a higher version number, though? You can use newer Anki versions with ankisyncd without even touching anki-bundled, it's only supposed to point to a well-tested version in case the one you have on the server doesn't work with ankisyncd.

**Comment by TooYoungTooSimp** [comment]
#54 
After some investigation through ankitects/anki .
I found
https://github.com/ankitects/anki/blob/8b6cce52e12ca834ead55df544d80307a6b080ea/pylib/anki/sync.py#L98
and
https://github.com/ankitects/anki/blob/b821209f83ab8c78d1af9c1fc64ba5c9d9fdbd32/pylib/anki/collection.py#L132-L135

It seems that `offset` is only a timezone based parameter and I think it may not so important at all.
So I passed the `raise` statement.

I've tested on my all devices which all enabled v2 sched and all of them seem working perfectly.

Pull request updated.

**Comment by genedan** [comment]
@TooYoungTooSimp , I've tried implementing this, but when I use AnkiDroid to sync, sometimes I get asked to perform a full sync because the database is in an inconsistent state.

Specifically, this happens when I have a subdeck with some actively lapsed cards that's part of a larger deck. Having no lapsed cards to review lets me sync normally though.

I'm not sure if this is due to AnkiDroid, Anki, or anki-sync-server. AnkiDroid syncs okay with AnkiWeb and the desktop version of Anki syncs just fine when I use anki-sync-server.

**Comment by TooYoungTooSimp** [comment]
@genedan I think it may be caused by a anki desktop change, it's database structure seems changed recent ly. I'm using old versions to temporary avoid this problem.

**Comment by genedan** [comment]
Just an update on this...the issue I had definitely was on AnkiDroid's side which had been fixed. I've been using this PR for the last few months and haven't had any issues since.

**Comment by shanehh** [comment]
> Just an update on this...the issue I had definitely was on AnkiDroid's side which had been fixed. I've been using this PR for the last few months and haven't had any issues since.

Unfortunately, it's not working for my AnkiDroid(2.13.4 latest in google play). If I enable v2 scheduler and even ONLY do one card review, there will be an inconsistent state.

**Comment by inevity** [comment]
> Just an update on this...the issue I had definitely was on AnkiDroid's side which had been fixed. I've been using this PR for the last few months and haven't had any issues since.

@genedan ,which ankidroid version have this fix?

**Pull request closed without merging**
