### PR TITLE
Fix long media sync times on AnkiDroid

### LINKED ISSUE #26: Long media sync times
Is anyone noticing a long sync time for media changes, for those of you who have a large collection? It's 15 minutes on my end. Sometimes it fails, so I have to resync and wait another 15 min, etc. 

To reproduce the issue, simply have a large media collection (I have 40k files), make some media changes, and then sync.

I'm not sure if the issue is on the side of AnkiDroid or ankisyncd, just my observations.

### PR DESCRIPTION
**Pull request by Marth68**
Closes #26. The server was always sending metadata for all files in the collection as a response to the mediaChanges operation. Because AnkiDroid then calculates checksums for all these files (just to notice that they actually haven't changed), it took larger collections very long to sync after every media change. With this fix, only the number of files indicated by usn - lastUsn (and mtime) are considered for each sync. By also updating mtime for deleted files, they will be correctly considered.

### CODE REVIEW

**Comment by tsudoko** [comment]
The general idea is good, but I don't agree with using mtime for determining which files should be synced. Mtime is a filesystem attribute and can be set to any value, not necessarily aligned with the actual time the file was last added/modified/deleted. (It is true that ankisyncd doesn't actually preserve the media files' mtime as sent by the client at the moment, though.) It also poses problems when multiple files are modified at the same time, since they would have the same mtime. I've run into this problem while writing dfc473c0840f874413f85733ea4b94d9e3c1cb41. The whole test takes less than a second to run, so all files had the same mtime and the server did not pick the right files.

If I'm not missing anything, the correct indicator of a file's recentness would be the `usn` from the last sync it was modified in. Per-file `usn`s are currently not stored in the media DB, so the schema would need to be changed. Thoughts?

**Comment by Marth68** [comment]
Yes, the absolute indicator of recentness for each file is the usn of the sync it was last modified in, as you say. I also thought about extending the database schema to store the usns for a more theoretically stable solution. But this is defined by the main Anki modules and is therefore not part of ankisyncd, so changing it could get quite nasty. Maybe there is an elegant way to do it, but I don't know what the individual Anki modules do too well. I would generally advise against changing any of Anki's code for this. What I know is that Anki internally solves this problems by using a dirty bit (technically it's an integer), which of course is only sufficient from a client's point of view. (But if none of the calls from ankisyncd indirectly cause it to be changed, we could probably use this field for usns?) If you're up for it, you could also implement another small database managed by ankisyncd mapping file names onto "last modified" usns, similar to the existing authentication and session databases.

I appreciate you testing the changes thoroughly beforehand and think that this is a good practice by all means, but in this case, it probably creates problems that wouldn't be there in any realistic scenario. Would mtime have milliseconds and maybe also nanoseconds precision, the files would have been sorted correctly. But it doesn't – because files usually don't tend to get modified twice within the span of a second. Realistically, no (normal, non-hacking) user of Anki would be able to sync, sync another client, make a media change and sync again in this time. I think that using mtime is a pragmatic and minimally invasive solution that also fixes the problem users are experiencing. To be honest, I wouldn't have used the server without this fix because I mainly sync between Anki 2.1 and AnkiDroid, and media syncs took about an hour on my device.

Anyway, thank you for your efforts of making this project available! It's great to be finally independent from AnkiWeb and still be able to use all the clients.

**Comment by tsudoko** [comment]
> But this is defined by the main Anki modules and is therefore not part of ankisyncd, so changing it could get quite nasty. (...) I would generally advise against changing any of Anki's code for this.

It is true that currently the media files are managed by the `anki.media.MediaManager` class, but they don't have to be. `SyncMediaHandler` could use a custom-made media DB that doesn't depend on any Anki code instead if someone were to implement it.

> If you're up for it, you could also implement another small database managed by ankisyncd mapping file names onto "last modified" usns, similar to the existing authentication and session databases.

I was thinking about it, but it seems a bit ugly compared to storing them in a single DB. One advantage of such an approach would be complete backward and forward compatibility, though.

> in this case, it probably creates problems that wouldn't be there in any realistic scenario. Would mtime have milliseconds and maybe also nanoseconds precision, the files would have been sorted correctly. But it doesn't – because files usually don't tend to get modified twice within the span of a second. Realistically, no (normal, non-hacking) user of Anki would be able to sync, sync another client, make a media change and sync again in this time.

While this is true — and your solution is perfectly acceptable as a workaround — I do not want to merge code that fails to do the job in *some* conditions, even if they're highly unlikely to be true at the moment, especially when a solution that would cover 100% of the cases exists and isn't overly complicated. I'm also not feeling comfortable with introducing a non-immediately-obvious relationship between the media files' mtime and the decision whether or not they should be sent from/to a given client. It would be visible in the code, sure, but unlike usn, it wasn't meant to be used for that purpose, so one would need to actually look at the implementation to find out.

Don't get me wrong, I really appreciate the fact you've made this PR since the general idea is great, I'm just afraid using mtime here could possibly break something else (other than my test) sometime in the future because of something I couldn't predict right now (e.g. an unintended side effect from an unrelated code change (possibly in Anki itself) or some unexpected edge case). Using usn makes that risk much less likely. I am aware this risk might already be miniscule depending on the circumstances, but I just wouldn't feel right merging this.

---

I'll need to think about this, right now I'm not fully sure which approach would be ideal. In the meantime I'll recommend using your PR as an interim solution. I've recently realized writing code can be a lot harder when it actually has users.

> Anyway, thank you for your efforts of making this project available! It's great to be finally independent from AnkiWeb and still be able to use all the clients.

Just to be clear, keep in mind I'm not the one who created this, I'm merely keeping it alive. This started out as a personal fork that happened to gain users. I'm still quite bad at this maintenance thing, since I imagine it would be a lot easier to e.g. introduce possibly breaking changes if I had, say, a proper release process. I guess I didn't expect people who aren't me to actually use my fork.

**Comment by Marth68** [comment]
It's all right, I just wanted to point you to the problem, since nobody in #26 seemed to have found out what the cause was. You decide. But I got some last comments that might interest you about why I thought this would be worth an actual commit:

> I do not want to merge code that fails to do the job in some conditions, even if they're highly unlikely to be true at the moment, especially when a solution that would cover 100% of the cases exists and isn't overly complicated. I'm also not feeling comfortable with introducing a non-immediately-obvious relationship between the media files' mtime and the decision whether or not they should be sent from/to a given client.

In the very likely situation of having a good number of media files in your collection and wanting to sync with AnkiDroid, the current code fails to do the job (acceptably) in _all_ conditions. That's why I think every user synching with AnkiDroid will want to have this issue fixed.
With regards to mtime, I actually think it is semantically unambiguous. As an attribute of media files, mtime (modification time) can only be the time each file was last modified. As long as the database schema is correctly set up, sorting by mtime will always yield the most recently modified files. With that in mind, the relationship between mtime and relevance for synchronization is obvious, since we effectively only ever synchronize files that have been modified at any point in time since the last sync.
As I understand it, this fix is only affecting the procedure of syncing a client from the server. It will not affect the procedure of syncing the server because the clients use their dirty bit for this.

> Just to be clear, keep in mind I'm not the one who created this, I'm merely keeping it alive.

I'm aware of this, so thanks for keeping it alive! I didn't find any other project that had been updated recently and provided support for both Anki 2.1 and AnkiDroid...

**Comment by tsudoko** [comment]
Done in ac1920d0786725b3e6a3f23b52cd986ca6b13c7b...3b8fe9e7f346cfb749bb7b045212d1e4ff2410ed. I ended up implementing a small server-specific media DB. The way it's currently plugged into the `_Collection` objects is ugly, but it works.

**Comment by Marth68** [comment]
Awesome! Thanks for making the effort! I think this is the best solution for a server that is using a back-end designed for clients. Some things need to be managed separately...

**Pull request closed without merging**
